// DEFINE Y_X_Z NUMBER

// no state
#define NONE 0

// front layer
#define UP_LEFT_FRONT 1
#define UP_MIDDLE_FRONT 2
#define UP_RIGHT_FRONT 3
#define MIDDLE_LEFT_FRONT 4
#define MIDDLE_MIDDLE_FRONT 5
#define MIDDLE_RIGHT_FRONT 6
#define DOWN_LEFT_FRONT 7
#define DOWN_MIDDLE_FRONT 8
#define DOWN_RIGHT_FRONT 9

// middle layer
#define UP_LEFT_MIDDLE 10
#define UP_MIDDLE_MIDDLE 11
#define UP_RIGHT_MIDDLE 12
#define MIDDLE_LEFT_MIDDLE 13
#define MIDDLE_MIDDLE_MIDDLE 14
#define MIDDLE_RIGHT_MIDDLE 15
#define DOWN_LEFT_MIDDLE 16
#define DOWN_MIDDLE_MIDDLE 17
#define DOWN_RIGHT_MIDDLE 18

// rear layer
#define UP_LEFT_REAR 19
#define UP_MIDDLE_REAR 20
#define UP_RIGHT_REAR 21
#define MIDDLE_LEFT_REAR 22
#define MIDDLE_MIDDLE_REAR 23
#define MIDDLE_RIGHT_REAR 24
#define DOWN_LEFT_REAR 25
#define DOWN_MIDDLE_REAR 26
#define DOWN_RIGHT_REAR 27

// areas for moving
#define UP_LEFT 51
#define UP_MIDDLE 52
#define UP_RIGHT 53
#define MIDDLE_LEFT 54
#define MIDDLE_MIDDLE 55
#define MIDDLE_RIGHT 56
#define DOWN_LEFT 57
#define DOWN_MIDDLE 58
#define DOWN_RIGHT 59
